db:
  driver: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  username: sa
  password: sa
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  hbm2ddl: update
  use_second_level_cache: true
  region_factory: org.hibernate.cache.ehcache.EhCacheRegionFactory
  use_query_cache: true
entityManager.packagesToScan: springboothibernate
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  main:
    allow-circular-references: true
management:
  endpoints:
    web:
      exposure:
        include=*:

